export const metadata = {
  title: " Learn Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header
          style={{
            backgroundColor: "Cyan",
            padding: "0.5rem",
          }}
        >
          <p>Header</p>
        </header>
        <p style={{ height: "80vh", margin: "auto" }}>{children}</p>
        <footer
          style={{
            backgroundColor: "ghostwhite",
            padding: "1rem",
            position: "relative",
          }}
        >
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
