import Link from "next/link";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function Home() {
  return (
    <>
      {" "}
      <h1>Welcome Home!</h1>
      <nav>
        <Link href="/blog" style={{ margin: "1rem" }}>
          Blog
        </Link>
        <Link href="/about" style={{ margin: "1rem" }}>
          About
        </Link>
        <Link href="/products" style={{ margin: "1rem" }}>
          Products
        </Link>
      </nav>
    </>
  );
}
